version: '3.8'
services:
  pokemon-database:
    image: postgres:latest
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  pokemon-app:
    image: pokemon-app
    ports:
      - '8080:8080'
    volumes:
      - ./.env:/app/.env
    build: ./
    depends_on:
      pokemon-database:
        condition: service_started

networks:
  data:
